### ISSUE TITLE
Automatically update pfp

### ISSUE THREAD

**Issue by esau-morais** [harshhhdev/www#24]
I love your website and just wanted to remind that if you use https://github.com/your-username.png, it'll automatically change your pfp

https://github.com/harshhhdev/www/blob/master/src/components/Home/Intro.tsx#L25

**Comment by harshhhdev** [comment]
oh hey, thanks for the tip and your kind words. i'm in the process of upgrading my site (#23), and i'll be sure to add it onto the new version.
